# Generated by Django 4.2 on 2023-04-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_request_technicalspecialist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalspecialist',
            name='members',
        ),
        migrations.CreateModel(
            name='TechnicalSpecialistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='team_members', to='api.technicalspecialist')),
            ],
        ),
        migrations.AddField(
            model_name='technicalspecialist',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='api.technicalspecialistgroup'),
            preserve_default=False,
        ),
    ]
