# Generated by Django 4.2 on 2023-04-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_client_password_remove_client_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalspecialist',
            old_name='specialist',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='technicalsupportoperator',
            old_name='operator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='technicalspecialist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='technicalspecialist',
            name='username',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
